GET http://localhost:5000/auth


###

GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/5f9889739db92c36e0a8d305

###

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "username": "theo-js",
    "age": 26,
    "email": "dev.js.theo@gmail.com"
}