# GET ALL USERS
GET http://localhost:5000/api/users

###
# GET SPECIFIC USER
GET http://localhost:5000/api/users/:uid

###
# SIGN UP
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "username": "theo-js",
    "age": 26,
    "email": "dev.js.theo@gmail.com",
    "password": "lolololol",
    "confirmation": "lolololol"
}

###
# LOGIN
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "email": "dev.js.theo@gmail.com",
    "password": "lolololol"
}

###
# GET CURRENTLY LOGGED IN USER
GET http://localhost:5000/api/auth/user
X-Auth-Token: 

###
# GET ITEMS
GET http://localhost:5000/api/items
X-Auth-Token: 


###
# DELETE ACCOUNT
DELETE http://localhost:5000/api/users/:uid
X-Auth-Token: 